import type { ValueFormatterParams } from "ag-grid-community";

export const productsData = [
  {
    id: 1,
    name: 'Hydraulic Hose 1/4"',
    price: 120,
    quantity: 50,
    category: "Hoses",
    Hsn: 400921,
  },
  {
    id: 2,
    name: 'Hydraulic Hose 3/8"',
    price: 150,
    quantity: 40,
    category: "Hoses",
    Hsn: 400922,
  },
  {
    id: 3,
    name: 'Hydraulic Hose 1/2"',
    price: 180,
    quantity: 35,
    category: "Hoses",
    Hsn: 400923,
  },
  {
    id: 4,
    name: 'Hydraulic Hose 3/4"',
    price: 220,
    quantity: 30,
    category: "Hoses",
    Hsn: 400924,
  },
  {
    id: 5,
    name: 'Hydraulic Hose 1"',
    price: 260,
    quantity: 25,
    category: "Hoses",
    Hsn: 400925,
  },
  {
    id: 6,
    name: 'Straight Fitting 1/4"',
    price: 40,
    quantity: 100,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 7,
    name: 'Straight Fitting 3/8"',
    price: 45,
    quantity: 90,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 8,
    name: 'Straight Fitting 1/2"',
    price: 50,
    quantity: 80,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 9,
    name: 'Elbow Fitting 1/4"',
    price: 55,
    quantity: 70,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 10,
    name: 'Elbow Fitting 3/8"',
    price: 60,
    quantity: 65,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 11,
    name: 'Elbow Fitting 1/2"',
    price: 65,
    quantity: 60,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 12,
    name: 'Tee Fitting 1/4"',
    price: 70,
    quantity: 55,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 13,
    name: 'Tee Fitting 3/8"',
    price: 75,
    quantity: 50,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 14,
    name: 'Tee Fitting 1/2"',
    price: 80,
    quantity: 45,
    category: "Fittings",
    Hsn: 730799,
  },
  {
    id: 15,
    name: 'Hydraulic Adapter 1/4" BSP',
    price: 35,
    quantity: 100,
    category: "Adapters",
    Hsn: 730799,
  },
  {
    id: 16,
    name: 'Hydraulic Adapter 3/8" BSP',
    price: 38,
    quantity: 90,
    category: "Adapters",
    Hsn: 730799,
  },
  {
    id: 17,
    name: 'Hydraulic Adapter 1/2" BSP',
    price: 42,
    quantity: 80,
    category: "Adapters",
    Hsn: 730799,
  },
  {
    id: 18,
    name: 'Quick Coupler 1/4"',
    price: 120,
    quantity: 30,
    category: "Couplers",
    Hsn: 848120,
  },
  {
    id: 19,
    name: 'Quick Coupler 3/8"',
    price: 130,
    quantity: 28,
    category: "Couplers",
    Hsn: 848120,
  },
  {
    id: 20,
    name: 'Quick Coupler 1/2"',
    price: 140,
    quantity: 25,
    category: "Couplers",
    Hsn: 848120,
  },
  {
    id: 21,
    name: "Hydraulic Clamp Small",
    price: 25,
    quantity: 120,
    category: "Clamps",
    Hsn: 732690,
  },
  {
    id: 22,
    name: "Hydraulic Clamp Medium",
    price: 30,
    quantity: 110,
    category: "Clamps",
    Hsn: 732690,
  },
  {
    id: 23,
    name: "Hydraulic Clamp Large",
    price: 35,
    quantity: 100,
    category: "Clamps",
    Hsn: 732690,
  },
  {
    id: 24,
    name: "Pressure Gauge 0-100 bar",
    price: 200,
    quantity: 15,
    category: "Gauges",
    Hsn: 902620,
  },
  {
    id: 25,
    name: "Pressure Gauge 0-250 bar",
    price: 250,
    quantity: 12,
    category: "Gauges",
    Hsn: 902620,
  },
  {
    id: 26,
    name: "Pressure Gauge 0-400 bar",
    price: 300,
    quantity: 10,
    category: "Gauges",
    Hsn: 902620,
  },
  {
    id: 27,
    name: "Hydraulic Oil Seal 25mm",
    price: 15,
    quantity: 200,
    category: "Seals",
    Hsn: 401693,
  },
  {
    id: 28,
    name: "Hydraulic Oil Seal 40mm",
    price: 18,
    quantity: 180,
    category: "Seals",
    Hsn: 401693,
  },
  {
    id: 29,
    name: "Hydraulic Oil Seal 50mm",
    price: 22,
    quantity: 160,
    category: "Seals",
    Hsn: 401693,
  },
  {
    id: 30,
    name: "Hydraulic Pump 1HP",
    price: 3500,
    quantity: 5,
    category: "Pumps",
    Hsn: 841360,
  },
  {
    id: 31,
    name: "Hydraulic Pump 2HP",
    price: 4800,
    quantity: 4,
    category: "Pumps",
    Hsn: 841360,
  },
  {
    id: 32,
    name: "Hydraulic Pump 3HP",
    price: 6000,
    quantity: 3,
    category: "Pumps",
    Hsn: 841360,
  },
  {
    id: 33,
    name: "Return Line Filter",
    price: 400,
    quantity: 20,
    category: "Filters",
    Hsn: 842129,
  },
  {
    id: 34,
    name: "Suction Filter",
    price: 350,
    quantity: 22,
    category: "Filters",
    Hsn: 842129,
  },
  {
    id: 35,
    name: "Inline Filter",
    price: 450,
    quantity: 18,
    category: "Filters",
    Hsn: 842129,
  },
  {
    id: 36,
    name: "Hydraulic Cylinder 50mm",
    price: 2500,
    quantity: 6,
    category: "Cylinders",
    Hsn: 841221,
  },
];
export const customersData = [
  {
    id: 1,
    name: "Ravi Kumar",
    organisation: "HydroFlex",
    gstRegistered: true,
    address: "12, Industrial Area, Chennai",
    mobile: "9876543210",
    gst: "33AAAAA0000A1Z5",
  },
  {
    id: 2,
    name: "Suresh Patel",
    organisation: "HoseMart",
    gstRegistered: false,
    address: "45, Market Road, Coimbatore",
    mobile: "9123456780",
    gst: "",
  },
  {
    id: 3,
    name: "Priya Sharma",
    organisation: "Fluid Connect",
    gstRegistered: true,
    address: "78, Main Street, Madurai",
    mobile: "9988776655",
    gst: "33BBBBB1111B2Z6",
  },
  {
    id: 4,
    name: "Anil Mehta",
    organisation: "Fittings World",
    gstRegistered: true,
    address: "23, Anna Nagar, Salem",
    mobile: "9090909090",
    gst: "33CCCCC2222C3Z7",
  },
  {
    id: 5,
    name: "Deepa Singh",
    organisation: "HydroParts",
    gstRegistered: false,
    address: "56, Gandhi Road, Trichy",
    mobile: "9008007006",
    gst: "",
  },
  {
    id: 6,
    name: "Vikram Rao",
    organisation: "Hose Experts",
    gstRegistered: true,
    address: "89, Cross Road, Erode",
    mobile: "9876501234",
    gst: "33DDDDD3333D4Z8",
  },
  {
    id: 7,
    name: "Meena Iyer",
    organisation: "FlexiHose",
    gstRegistered: false,
    address: "34, South Street, Vellore",
    mobile: "9123456701",
    gst: "",
  },
  {
    id: 8,
    name: "Rajesh Gupta",
    organisation: "Hydraulic Hub",
    gstRegistered: true,
    address: "67, North Avenue, Tiruppur",
    mobile: "9988776611",
    gst: "33EEEEE4444E5Z9",
  },
  {
    id: 9,
    name: "Kavitha R",
    organisation: "Hose Junction",
    gstRegistered: false,
    address: "21, West Road, Thanjavur",
    mobile: "9090909012",
    gst: "",
  },
  {
    id: 10,
    name: "Arun Prasad",
    organisation: "Fittings Point",
    gstRegistered: true,
    address: "43, East Street, Karur",
    mobile: "9008007012",
    gst: "33FFFFF5555F6Z0",
  },
  {
    id: 11,
    name: "Sathish Kumar",
    organisation: "HydroLink",
    gstRegistered: true,
    address: "12, Main Road, Namakkal",
    mobile: "9876543221",
    gst: "33GGGGG6666G7Z1",
  },
  {
    id: 12,
    name: "Lakshmi Narayanan",
    organisation: "Hose Depot",
    gstRegistered: false,
    address: "45, Market Lane, Dindigul",
    mobile: "9123456789",
    gst: "",
  },
  {
    id: 13,
    name: "Manoj Pillai",
    organisation: "Fluid Solutions",
    gstRegistered: true,
    address: "78, Industrial Estate, Hosur",
    mobile: "9988776654",
    gst: "33HHHHH7777H8Z2",
  },
  {
    id: 14,
    name: "Geetha S",
    organisation: "Fittings Store",
    gstRegistered: false,
    address: "23, Anna Salai, Kanchipuram",
    mobile: "9090909087",
    gst: "",
  },
  {
    id: 15,
    name: "Naveen Raj",
    organisation: "HydroMart",
    gstRegistered: true,
    address: "56, Gandhi Nagar, Pudukkottai",
    mobile: "9008007005",
    gst: "33IIIII8888I9Z3",
  },
  {
    id: 16,
    name: "Shalini Menon",
    organisation: "Hose House",
    gstRegistered: true,
    address: "89, Cross Street, Sivakasi",
    mobile: "9876501235",
    gst: "33JJJJJ9999J0Z4",
  },
  {
    id: 17,
    name: "Prakash Reddy",
    organisation: "Hydraulic Store",
    gstRegistered: false,
    address: "34, South Avenue, Cuddalore",
    mobile: "9123456702",
    gst: "",
  },
  {
    id: 18,
    name: "Divya Mohan",
    organisation: "FlexiParts",
    gstRegistered: true,
    address: "67, North Road, Villupuram",
    mobile: "9988776612",
    gst: "33KKKKK0000K1Z5",
  },
  {
    id: 19,
    name: "Sundar P",
    organisation: "Hose Bazaar",
    gstRegistered: false,
    address: "21, West Avenue, Thoothukudi",
    mobile: "9090909013",
    gst: "",
  },
  {
    id: 20,
    name: "Ramesh Babu",
    organisation: "Fittings Mart",
    gstRegistered: true,
    address: "43, East Lane, Nagercoil",
    mobile: "9008007013",
    gst: "33LLLLL1111L2Z6",
  },
  {
    id: 21,
    name: "Karthik S",
    organisation: "HydroTech",
    gstRegistered: true,
    address: "12, Main Avenue, Tirunelveli",
    mobile: "9876543232",
    gst: "33MMMMM2222M3Z7",
  },
  {
    id: 22,
    name: "Anitha V",
    organisation: "Hose Solutions",
    gstRegistered: false,
    address: "45, Market Street, Perambalur",
    mobile: "9123456790",
    gst: "",
  },
  {
    id: 23,
    name: "Vijay Anand",
    organisation: "Fluid Mart",
    gstRegistered: true,
    address: "78, Industrial Road, Ariyalur",
    mobile: "9988776656",
    gst: "33NNNNN3333N4Z8",
  },
  {
    id: 24,
    name: "Preethi S",
    organisation: "Fittings Hub",
    gstRegistered: false,
    address: "23, Anna Nagar, Ramanathapuram",
    mobile: "9090909088",
    gst: "",
  },
  {
    id: 25,
    name: "Siva Kumar",
    organisation: "HydroParts",
    gstRegistered: true,
    address: "56, Gandhi Street, Virudhunagar",
    mobile: "9008007004",
    gst: "33OOOOO4444O5Z9",
  },
  {
    id: 26,
    name: "Gayathri R",
    organisation: "Hose Mart",
    gstRegistered: true,
    address: "89, Cross Avenue, Krishnagiri",
    mobile: "9876501236",
    gst: "33PPPPP5555P6Z0",
  },
  {
    id: 27,
    name: "Aravind S",
    organisation: "Hydraulic Depot",
    gstRegistered: false,
    address: "34, South Lane, Dharmapuri",
    mobile: "9123456703",
    gst: "",
  },
  {
    id: 28,
    name: "Mohan Raj",
    organisation: "FlexiMart",
    gstRegistered: true,
    address: "67, North Street, Theni",
    mobile: "9988776613",
    gst: "33QQQQQ6666Q7Z1",
  },
  {
    id: 29,
    name: "Sangeetha M",
    organisation: "Hose Point",
    gstRegistered: false,
    address: "21, West Street, Karur",
    mobile: "9090909014",
    gst: "",
  },
  {
    id: 30,
    name: "Vimal Kumar",
    organisation: "Fittings Depot",
    gstRegistered: true,
    address: "43, East Avenue, Nagapattinam",
    mobile: "9008007014",
    gst: "33RRRRR7777R8Z2",
  },
  {
    id: 31,
    name: "Kiran Kumar",
    organisation: "HydroStore",
    gstRegistered: true,
    address: "12, Main Lane, Sivagangai",
    mobile: "9876543243",
    gst: "33SSSSS8888S9Z3",
  },
  {
    id: 32,
    name: "Lavanya S",
    organisation: "Hose Solutions",
    gstRegistered: false,
    address: "45, Market Avenue, Tiruvarur",
    mobile: "9123456791",
    gst: "",
  },
  {
    id: 33,
    name: "Sathya Narayanan",
    organisation: "Fluid House",
    gstRegistered: true,
    address: "78, Industrial Street, Kanyakumari",
    mobile: "9988776657",
    gst: "33TTTTT9999T0Z4",
  },
  {
    id: 34,
    name: "Ragini R",
    organisation: "Fittings Solutions",
    gstRegistered: false,
    address: "23, Anna Avenue, Thiruvannamalai",
    mobile: "9090909089",
    gst: "",
  },
  {
    id: 35,
    name: "Murali S",
    organisation: "HydroMart",
    gstRegistered: true,
    address: "56, Gandhi Avenue, Pudukkottai",
    mobile: "9008007003",
    gst: "33UUUUU0000U1Z5",
  },
  {
    id: 36,
    name: "Nithya K",
    organisation: "Hose House",
    gstRegistered: true,
    address: "89, Cross Lane, Salem",
    mobile: "9876501237",
    gst: "33VVVVV1111V2Z6",
  },
  {
    id: 37,
    name: "Sridhar R",
    organisation: "Hydraulic Mart",
    gstRegistered: false,
    address: "34, South Avenue, Erode",
    mobile: "9123456704",
    gst: "",
  },
  {
    id: 38,
    name: "Kavitha S",
    organisation: "FlexiStore",
    gstRegistered: true,
    address: "67, North Avenue, Madurai",
    mobile: "9988776614",
    gst: "33WWWWW2222W3Z7",
  },
  {
    id: 39,
    name: "Ramesh S",
    organisation: "Hose Depot",
    gstRegistered: false,
    address: "21, West Lane, Coimbatore",
    mobile: "9090909015",
    gst: "",
  },
  {
    id: 40,
    name: "Sowmya R",
    organisation: "Fittings House",
    gstRegistered: true,
    address: "43, East Street, Chennai",
    mobile: "9008007015",
    gst: "33XXXXX3333X4Z8",
  },
  {
    id: 41,
    name: "Vijaya Kumar",
    organisation: "HydroLink",
    gstRegistered: true,
    address: "12, Main Street, Trichy",
    mobile: "9876543254",
    gst: "33YYYYY4444Y5Z9",
  },
  {
    id: 42,
    name: "Meera S",
    organisation: "Hose Mart",
    gstRegistered: false,
    address: "45, Market Road, Salem",
    mobile: "9123456792",
    gst: "",
  },
  {
    id: 43,
    name: "Sathish R",
    organisation: "Fluid Depot",
    gstRegistered: true,
    address: "78, Industrial Avenue, Vellore",
    mobile: "9988776658",
    gst: "33ZZZZZ5555Z6Z0",
  },
  {
    id: 44,
    name: "Priyanka S",
    organisation: "Fittings Mart",
    gstRegistered: false,
    address: "23, Anna Lane, Tiruppur",
    mobile: "9090909090",
    gst: "",
  },
  {
    id: 45,
    name: "Arjun S",
    organisation: "HydroParts",
    gstRegistered: true,
    address: "56, Gandhi Street, Karur",
    mobile: "9008007002",
    gst: "33AAAAA6666A7Z1",
  },
  {
    id: 46,
    name: "Divakar R",
    organisation: "Hose Solutions",
    gstRegistered: true,
    address: "89, Cross Avenue, Thanjavur",
    mobile: "9876501238",
    gst: "33BBBBB7777B8Z2",
  },
  {
    id: 47,
    name: "Sangeetha K",
    organisation: "Hydraulic House",
    gstRegistered: false,
    address: "34, South Street, Dindigul",
    mobile: "9123456705",
    gst: "",
  },
  {
    id: 48,
    name: "Karthika S",
    organisation: "FlexiHub",
    gstRegistered: true,
    address: "67, North Lane, Cuddalore",
    mobile: "9988776615",
    gst: "33CCCCC8888C9Z3",
  },
  {
    id: 49,
    name: "Sundar R",
    organisation: "Hose Mart",
    gstRegistered: false,
    address: "21, West Avenue, Salem",
    mobile: "9090909016",
    gst: "",
  },
  {
    id: 50,
    name: "Vignesh S",
    organisation: "Fittings World",
    gstRegistered: true,
    address: "43, East Avenue, Chennai",
    mobile: "9008007016",
    gst: "33DDDDD9999D0Z4",
  },
];
export const fields = [
  { field: "name" },
  {
    field: "price",
    valueFormatter: (params: ValueFormatterParams) => {
      return "₹" + params.value.toLocaleString();
    },
  },
  { field: "quantity" },
  { field: "category" },
  { field: "Hsn" },
];
export const customerfields = [
  { field: "name" },
  { field: "organisation" },
  {
    field: "gstRegistered",
    valueFormatter: (params: ValueFormatterParams) =>
      params.value ? "Yes" : "No",
  },
  { field: "address" },
  { field: "mobile" },
  { field: "gst" },
];
